
export const ideaOperationsText = {
  ko: {
    submitSuccess: '아이디어가 성공적으로 제출되었습니다!',
    submitError: '아이디어 제출 중 오류가 발생했습니다.',
    analysisGenerated: 'AI 분석이 생성되었습니다!',
    analysisError: 'AI 분석 생성 중 오류가 발생했습니다.',
    verdictSaved: 'VC 평가가 저장되었습니다!',
    verdictError: 'VC 평가 저장 중 오류가 발생했습니다.',
    contentBlocked: '부적절한 콘텐츠가 감지되어 아이디어를 제출할 수 없습니다.',
    analysisWithFallback: 'AI 분석이 부분적으로 완료되었습니다.',
    lowScoreNotice: '점수가 낮게 나왔습니다. 더 구체적인 아이디어를 고려해보세요.',
    globalAnalysisGenerated: '🌍 글로벌 시장 분석이 완료되었습니다!',
    globalAnalysisError: '글로벌 분석 생성 중 오류가 발생했습니다.',
    highScoreNotice: '🎉 축하합니다! VC 전문가 조언 자격을 획득했습니다! (8점 이상 또는 월간 최다 하트)',
    rateLimitError: '분석 요청 한도에 도달했습니다. 잠시 후 다시 시도해주세요.',
    duplicateDetected: '유사한 아이디어가 이미 제출되었습니다. 더 독창적인 아이디어를 시도해보세요.',
    qualityCheckFailed: '아이디어 품질 기준을 충족하지 않습니다. 더 구체적이고 상세한 아이디어를 작성해주세요.',
  },
  en: {
    submitSuccess: 'Idea submitted successfully!',
    submitError: 'Error occurred while submitting idea.',
    analysisGenerated: 'AI analysis generated successfully!',
    analysisError: 'Error occurred while generating AI analysis.',
    verdictSaved: 'VC verdict saved successfully!',
    verdictError: 'Error occurred while saving VC verdict.',
    contentBlocked: 'Inappropriate content detected. Idea cannot be submitted.',
    analysisWithFallback: 'AI analysis partially completed.',
    lowScoreNotice: 'Low score received. Consider a more specific idea.',
    globalAnalysisGenerated: '🌍 Global Market Analysis Completed!',
    globalAnalysisError: 'Error occurred while generating global analysis.',
    highScoreNotice: '🎉 Congratulations! You qualify for VC expert advice! (8+ points or monthly top hearts)',
    rateLimitError: 'Analysis request limit reached. Please try again later.',
    duplicateDetected: 'Similar idea already submitted. Try a more original idea.',
    qualityCheckFailed: 'Idea does not meet quality standards. Please write a more specific and detailed idea.',
  }
};
