// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wutnxfgyikjisfqczyjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dG54Zmd5aWtqaXNmcWN6eWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDU1MTksImV4cCI6MjA2NTg4MTUxOX0.OYjyi2KvsdH5MjDT_RGYNWepuAOqM9Pv0YpeDrAAH4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);